### PR TITLE
adding enumerables

### PR DESCRIPTION
**Pull request by Bluette1**
## Description

The task was to implement some enumerable methods similar to the ones that exist in the Enumerables module in ruby.

This project is mainly about

-  Learning ruby syntax
-  Enumerables

## Live Demo

[Run on Repl.it](https://repl.it/github/Bluette1/enumerables)

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Marylene Batondana Sawyer**, I'm Sarah, your reviewer for this PR 👩‍🚀  

Great job with your Enumerable methods!

There's still a little error in my_any? though, check the comments below 🦾 

--------

## Changes Required 🏗️ 🐛 💡

- [ ] The my_any? method is not working as expected with the array below:
`[nil, false, nil, false].my_any?` 
The above should return false, not true.

- [ ] [OPTIONAL] You are turning off the rubocop verification for the length of the methods and complexity a lot. Please take a moment to consider how you can use this as an opportunity to refactor and make your code more modular instead.

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Bluette1** [comment]
Thank you very much @uryelah for the helpful review and encouraging feedback! I have made the required change.

**Comment by lekegitrepo** [comment]
#### Hi @Bluette1 :100: :1st_place_medal:
#### Good job for implementing the required changes. This project is approved :star:

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Comment by Bluette1** [comment]
@lekegitrepo, thank you very much!

**Pull request merged**
